services:
  traefik:
    image: ghcr.io/11notes/traefik:3.4.4
    read_only: true
    container_name: traefik
    restart: unless-stopped

    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "5432:5432/tcp" # Postgres

    volumes:
      - "var:/traefik/var"
      - ./traefik.yml:/traefik/etc/traefik.yml
      - "plugins:/plugins-storage" # plugins stored as volume because of read-only
    
    # Command line arguments (minimal, config in YAML)
    command:
      - "--configFile=/traefik/etc/traefik.yml"
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
      - "--ping.terminatingStatusCode=204"

    sysctls:
      net.ipv4.ip_unprivileged_port_start: 80 # allow rootless container to access port 80 and higher

    # Environment
    environment:
      TZ: "Europe/Stockholm"

    # Networks
    networks:
      - traefik_network
      
networks:
  traefik_network:
    driver: bridge

volumes:
  var:
  plugins: