http:
  services:
    authentik-backend:
      loadBalancer:
        servers:
          - url: "http://192.168.1.138:9000"
  routers:
    authentik:
      entryPoints:
        - websecure
      rule: "Host(`auth.tryy3.dev`)"
      service: authentik-backend
      tls:
        certResolver: letsencrypt
        domains:
          - main: "auth.tryy3.dev"