http:
  services:
    semaphore-backend:
      loadBalancer:
        servers:
          - url: "http://192.168.1.138:2222"
  routers:
    semaphore:
      entryPoints:
        - websecure
      rule: "Host(`semaphore.tryy3.dev`)"
      service: semaphore-backend
      tls:
        certResolver: letsencrypt
        domains:
          - main: "semaphore.tryy3.dev"