# http:
#   middlewares:
#     # Default security middlewares (matching 11notes defaults)
#     default-errors:
#       errors:
#         status:
#           - "402-599"
#         query: "/{status}"
#         service: default-errors
    
#     default-ratelimit:
#       rateLimit:
#         average: 100
#         burst: 120
#         period: 1s
    
#     default-ipallowlist-RFC1918:
#       ipAllowList:
#         sourceRange:
#           - "10.0.0.0/8"
#           - "172.16.0.0/12"
#           - "192.168.0.0/16"
    
#     # HTTP to HTTPS redirect
#     default-http:
#       redirectScheme:
#         permanent: true
#         scheme: https
    
#     # Authentik integration
#     authentik:
#       forwardAuth:
#         address: "http://authentik:9000/outpost.goauthentik.io/auth/traefik"
#         trustForwardHeader: true
#         authResponseHeaders:
#           - "X-authentik-username"
#           - "X-authentik-groups"
#           - "X-authentik-email"
    
#     # Security headers
#     security-headers:
#       headers:
#         frameDeny: true
#         sslRedirect: true
#         browserXssFilter: true
#         contentTypeNosniff: true
#         forceSTSHeader: true
#         stsIncludeSubdomains: true
#         stsPreload: true
#         stsSeconds: 31536000

#   # Default error service
#   services:
#     default-errors:
#       loadBalancer:
#         servers:
#           - url: "http://localhost:8080/api/rawdata"

api:
  insecure: true

log:
  level: DEBUG
  
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
  postgres:
    address: ":5432"

certificatesResolvers:
  letsencrypt:
    acme:
      dnsChallenge:
        provider: "dnsimple"
        resolvers:
          - 192.168.1.3:53
      email: dennistryy3@gmail.com
      storage: /traefik/var/acme.json

providers:
  file:
    directory:
      /traefik/config
  docker: {} 